# Generated by Django 6.0.7 on 2026-08-07 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Only used for private (DM) rooms — restricts who can join.', related_name='dm_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
