# Generated by Django 6.0.7 on 2026-08-10 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_readstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='accepted',
            field=models.BooleanField(default=True, help_text='False for a new DM until the recipient accepts (or replies).'),
        ),
        migrations.AddField(
            model_name='room',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='Who started this DM — only set for private rooms.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
